" fnamemodify from https://stackoverflow.com/a/18734557
let vim_scripts_dir = resolve(fnamemodify(resolve(expand('<sfile>:p')), ':h') . '/../vimscripts')

execute 'source' . vim_scripts_dir . '/Utils.vim'

call SourceIfExists(vim_scripts_dir, ['CommonPlugIns.vim'])

" Return plugin installation directory for vim-plug
function PlugInInstallDir()
    if has('nvim')
        return fnamemodify('~/.config/nvim/plugged', ':p')
    else
        return fnamemodify('~/.vim/plugged', ':p')
    endif
endfunction

call InitCommonPlugIns(PlugInInstallDir())
call ConfigCommonPlugIns(vim_scripts_dir, PlugInInstallDir())

:set mouse=r
syntax on

filetype plugin indent on
" show existing tab with 4 spaces width
set tabstop=4
" when indenting with '>', use 4 spaces width
set shiftwidth=4
" On pressing tab, insert 4 spaces
set expandtab
" Show line numbers
set number
" Use the desktop clipboard by default
let g:clipbrdDefaultReg = '+'
" Highlight all search hits
set hlsearch

" Highlight trailing whitespace
" From: https://vim.fandom.com/wiki/Highlight_unwanted_spaces
highlight ExtraWhitespace ctermbg=red guibg=red
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/

" Draw Column
" set colorcolumn=80,100
" highlight ColorColumn ctermbg=lightgrey guibg=lightgrey

" For tmux coloring
set background=dark
