# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = [
        "xhci_pci"
        "ahci"
        "nvme"
        "usb_storage"
        "sd_mod"
        "sdhci_pci"
      ];
      kernelModules = [ "i915" ];
    };
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/493990e9-1249-4fc1-a314-60f97a0a84e9";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/0DE7-78B2";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/a8296ca2-5ea9-4198-8138-75e18c7eff79"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s20f0u3u1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  # Enable Intel GPU hardware acceleration with VAAPI support
  # Suitable for 8th gen Intel CPUs (Coffee Lake) and newer

  # Enable graphics drivers and hardware acceleration
  hardware.graphics = {
    enableRedistributableFirmware = true;
    cpu.intel.updateMicrocode = true;
    enable = true;
    extraPackages = with pkgs; [
      # Intel VAAPI drivers
      intel-media-driver # iHD driver for Broadwell (5th gen) and newer
      intel-vaapi-driver # i965 driver (legacy, but useful fallback)

      # Additional codec support
      libvdpau-va-gl
      intel-compute-runtime # OpenCL support for Intel GPUs
    ];
  };

  # Ensure users can access GPU devices
  # The render group provides access to /dev/dri/renderD* devices
  users.groups.render = { };
}
