
[colors.bright]
black = "#5c6370"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#ffffff"
yellow = "#d19a66"

[colors.normal]
black = "#282c34"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#abb2bf"
yellow = "#d19a66"

[colors.primary]
background = "#282c34"
foreground = "#abb2bf"

[font]
size = 11.0

[font.bold]
family = "Fira Code Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Fira Code Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Fira Code Nerd Font"
style = "Italic"

[font.normal]
family = "Fira Code Nerd Font"
style = "Regular"
