# NOTE: All paths are relative to the scenario directories
---
dependency:
  name: galaxy
  options:
    # Relative to extensions directory from where the `molecule` command is run.
    requirements-file: ./molecule/resources/files/requirements.yml
    # Need to force reinstall local collections in order to get local changes.
    force: true
provisioner:
  name: ansible
  config_options:
    defaults:
      # Relative to scenario directory
      collections_path: ../../../../../.ansible/collections/
  playbooks:
    create: ../resources/playbooks/create.yml
    destroy: ../resources/playbooks/destroy.yml
platforms:
  - name: Fedora
    image: knipegp/fedora:36
  - name: Manjaro
    image: knipegp/manjarolinux:latest
