---
- name: Converge
  hosts: molecule
  tasks:
    - name: Test window manager role
      ansible.builtin.import_role:
        name: gknipe.personal.runs_window_manager
      vars:
        runs_window_manager_user: root
        runs_window_manager_wallpaper_directory: ~/.local/share/wallpapers
