---
- name: Install sway related software
  become: true
  block:
    - name: Install with Pacman
      when: ansible_distribution == "Archlinux"
      community.general.pacman:
        name:
          - sway
          - swaylock
          - bemenu-wayland
          - swaybg
          - ly
          - xorg-xwayland
          - dunst
          # screenshot
          # how do i call this from bemenu? `slurp | grim -g - - | wl-copy`
          - grim
          - wl-clipboard
          - slurp
          - udiskie
          - waybar
          - otf-font-awesome  # waybar requirement
          - brightnessctl  # needed for laptop brightness control
        state: present
        update_cache: true

    - name: Install with DNF
      when: ansible_distribution == "Fedora"
      ansible.builtin.dnf:
        name:
          - sway
          - bemenu
          - swaybg
          - xorg-x11-server-Xwayland
          - dunst
          - grim
          - wl-clipboard
          - slurp
          - udiskie
          - waybar
        state: present


- name: Get sway config directory paths
  ansible.builtin.set_fact:
    sway_config_dir: "{{ ansible_user_dir }}/.config/sway"

- name: Create sway config directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ runs_window_manager_user }}"
    group: "{{ runs_window_manager_user }}"
    mode: '0755'
  loop:
    - "{{ sway_config_dir }}"
    - "{{ sway_config_dir }}/config.d"

- name: Install sway config files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ runs_window_manager_user }}"
    group: "{{ runs_window_manager_user }}"
    mode: '0644'
  loop:
    - src: files/config
      dest: "{{ sway_config_dir }}/config"
    - src: files/wayland.conf
      dest: "{{ sway_config_dir }}/config.d/walyand.conf"
    - src: files/udiskie.conf
      dest: "{{ sway_config_dir }}/config.d/udiskie.conf"

- name: Install sway config files for laptop
  when: is_laptop
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ runs_window_manager_user }}"
    group: "{{ runs_window_manager_user }}"
    mode: '0644'
  loop:
    - src: files/laptop.conf
      dest: "{{ sway_config_dir }}/config.d/laptop.conf"

- name: Install ly
  when: ansible_distribution == "Archlinux"
  block:
    - name: Install with Pacman
      become: true
      community.general.pacman:
        name:
          - ly
        state: present

    - name: Disable currently running display manager
      become: true
      block:
        - name: Disable display-manager.service
          ansible.builtin.systemd:
            name: display-manager
            enabled: false
      rescue:
        - name: Print debug
          ansible.builtin.debug:
            msg: display-manager.service does not exist

    - name: Enable ly-dm
      become: true
      ansible.builtin.systemd:
        name: ly
        enabled: true

    - name: Install Ly config
      become: true
      ansible.builtin.copy:
        src: ly_config.ini
        dest: /etc/ly/config.ini
        owner: root
        group: root
        mode: '0755'

- name: >-
    Create wallpapers directory {{ runs_window_manager_wallpaper_directory }}
  ansible.builtin.file:
    path: "{{ runs_window_manager_wallpaper_directory }}"
    state: directory
    mode: '0755'

- name: Download wallpaper at "{{ item }}"
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: >-
      {{
        runs_window_manager_wallpaper_directory
      }}/{{ item.split('/')[-1].split('.') | join('_1920x1080.') }}
    mode: '0644'
  loop:
    - https://i.imgur.com/7mtcJ3S.jpeg

- name: Install Spotify
  block:
    - name: Install Snap
      become: true
      block:
        - name: Install with pacman
          when: ansible_distribution == "Archlinux"
          community.general.pacman:
            name: snapd
            state: present

    - name: Install from Snapcraft
      when: (ansible_connection | default(null)) != "containers.podman.podman"
      community.general.snap:
        name: spotify

- name: Install miscellaneous software
  become: true
  block:
    - name: Install with Pacman
      when: ansible_distribution == "Archlinux"
      community.general.pacman:
        name:
          - libreoffice-still
        state: present
        update_cache: true
