---
- name: Install role dependencies
  become: true
  block:
    - name: Install with Pacman
      when: ansible_distribution == "Archlinux"
      community.general.pacman:
        name:
          - git
          - fontconfig
          - ttf-fira-code
        state: present
        update_cache: true
      register: _arch_install

    - name: Install with DNF
      when: ansible_distribution == "Fedora"
      ansible.builtin.dnf:
        name:
          - git
          - fontconfig
          - fira-code-fonts
        state: present
      register: _fedora_install

- name: Get installed fonts
  ansible.builtin.command: fc-list
  changed_when: false
  register: _installed_fonts

- name: Install Nerd Font
  when: '"FiraCodeNerdFont" not in _installed_fonts.stdout'
  block:
    - name: Create temporary directory
      ansible.builtin.tempfile:
        state: directory
      register: _temp_directory

    - name: Assign repo destination
      ansible.builtin.set_fact:
        _nerd_fonts_directory: >-
          {{ (_temp_directory.path, 'nerd-fonts') | path_join }}

    # (2023-08-28) This repo is enormous so it's easiest to do a sparse
    # checkout.  Can't do that with the git module.
    - name: Clone Nerd Fonts  # noqa: command-instead-of-module
      ansible.builtin.command: >-
        git clone --filter=blob:none --sparse
        https://github.com/ryanoasis/nerd-fonts.git {{ _nerd_fonts_directory }}
      changed_when: true

    - name: Sparse checkout FiraCode  # noqa: command-instead-of-module
      ansible.builtin.command: git sparse-checkout add patched-fonts/FiraCode
      args:
        chdir: "{{ _nerd_fonts_directory }}"
      changed_when: true

    - name: Install Fira Code Nerd Font
      ansible.builtin.command: "{{ _nerd_fonts_directory }}/install.sh FiraCode"
      changed_when: true
