---
- name: Install photo management applications
  become: true
  block:
    - name: Install with pacman
      when: ansible_distribution == "Archlinux"
      community.general.pacman:
        name: darktable
        state: present
        update_cache: true

    - name: Install with DNF
      when: ansible_distribution == "Fedora"
      ansible.builtin.dnf:
        name: darktable
        state: present

- name: Install Spotify
  block:
    - name: Install Flatpak
      become: true
      block:
        - name: Install with pacman
          when: ansible_distribution == "Archlinux"
          community.general.pacman:
            name: flatpak
            state: present

        - name: Install with DNF
          when: ansible_distribution == "Fedora"
          ansible.builtin.dnf:
            name: flatpak
            state: present

    - name: Install from Flathub
      when: (ansible_connection | default(null)) != "containers.podman.podman"
      community.general.flatpak:
        name: com.spotify.Client
        state: present
