---
- name: Install photo management applications
  become: true
  block:
    - name: Install with pacman
      when: ansible_distribution == "Archlinux"
      community.general.pacman:
        name:
          - darktable
          - portmidi  # darktable optional dependency required to open the app
          - signal-desktop
        state: present
        update_cache: true

    - name: Install with DNF
      when: ansible_distribution == "Fedora"
      ansible.builtin.dnf:
        name: darktable
        state: present
