---
- name: Run meta checks
  hosts: all
  tasks:
    - name: Check for become password
      become: true
      ansible.builtin.debug:
        msg: Pass

- name: Install packages
  hosts: all
  roles:
    - photo_manager
    - role: runs_window_manager
      vars:
        window_manager_user: griff
      tags:
        - install_window_manager
