---
- name: Converge
  hosts: molecule
  tasks:
    - name: Set shell user
      ansible.builtin.set_fact:
        shell_user: root

    - name: Test power tools role
      ansible.builtin.import_role:
        name: gknipe.personal.power_tools
      vars:
        power_tools_user: root
