---
- name: Get config directory
  ansible.builtin.set_fact:
    _config_directory: >-
      {{ (power_tools_user_home, destination | dirname) | path_join }}

- name: Create config directory
  ansible.builtin.file:
    path: "{{ (power_tools_user_home, destination | dirname) | path_join }}"
    state: directory
    mode: "0755"

- name: Install config
  ansible.builtin.copy:
    src: "{{ source }}"
    dest: "{{ (power_tools_user_home, destination) | path_join }}"
    mode: "0644"
