---
- name: Install misc packages
  become: true
  block:
    - name: Install packages with Pacman
      when: ansible_distribution == "Archlinux"
      community.general.pacman:
        name:
          - git
          - ripgrep
          - fd
          - bat
          - exa
          - git-delta
          - neovim
          - alacritty
          - tealdeer
          - neofetch
          - gnupg
          - gparted
          - procs
          - starship
          - shellcheck
          - jq
          - openssh
          - sd
          - tokei
          # Ansible controller tools
          - podman
          - fuse-overlayfs
        state: present
        update_cache: true

    - name: Install packages with DNF
      when: ansible_distribution == "Fedora"
      ansible.builtin.dnf:
        name:
          - git
          - ripgrep
          - fd-find
          - bat
          - exa
          - git-delta
          - neovim
          - alacritty
          - tealdeer
          - neofetch
          - gnupg2
          - gparted
          - procs
          - starship
          - ShellCheck
          - tokei
          - fuse-overlayfs
          - jq
          - openssh
        state: present

- name: Get user info
  ansible.builtin.getent:
    database: passwd
    key: "{{ power_tools_user }}"

- name: Get user home directory
  ansible.builtin.set_fact:
    _user_home: "{{ ansible_facts.getent_passwd[power_tools_user][4] }}"

- name: Install dotfile for
  ansible.builtin.include_tasks:
    file: install_dotfile.yml
  vars:
    power_tools_user_home: "{{ _user_home }}"
    source: "{{ item.src }}"
    destination: "{{ item.dest }}"
  loop: "{{ power_tools_dotfile_locations }}"


- name: Set Nvim as git editor
  community.general.git_config:
    name: core.editor
    scope: global
    value: nvim

- name: Install shell extensions
  ansible.builtin.copy:
    src: power_tools.sh
    dest: "{{ (_user_home, '.bashrc.d/power_tools.sh') | path_join }}"
    mode: "0755"

- name: Install Starship config
  ansible.builtin.copy:
    src: starship.toml
    dest: "{{ (_user_home, '.config/starship.toml') | path_join }}"
    mode: "0755"
